export const donViList = [
  "Chi hội phụ nữ Công an phường Âu Cơ",
  "Chi hội phụ nữ Công an phường Hòa Bình",
  "Chi hội phụ nữ Công an phường Kỳ Sơn",
  "Chi hội phụ nữ Công an phường Nông Trang",
  "Chi hội phụ nữ Công an phường Phong Châu",
  "Chi hội phụ nữ Công an phường Phú Thọ",
  "Chi hội phụ nữ Công an phường Phúc Yên",
  "Chi hội phụ nữ Công an phường Tân Hòa",
  "Chi hội phụ nữ Công an phường Thanh Miếu",
  "Chi hội phụ nữ Công an phường Thống Nhất",
  "Chi hội phụ nữ Công an phường Vân Phú",
  "Chi hội phụ nữ Công an phường Việt Trì",
  "Chi hội phụ nữ Công an phường Vĩnh Phúc",
  "Chi hội phụ nữ Công an phường Vĩnh Yên",
  "Chi hội phụ nữ Công an phường Xuân Hòa",
  "Chi hội phụ nữ Công an xã An Bình",
  "Chi hội phụ nữ Công an xã An Nghĩa",
  "Chi hội phụ nữ Công an xã Bản Nguyên",
  "Chi hội phụ nữ Công an xã Bằng Luân",
  "Chi hội phụ nữ Công an xã Bao La",
  "Chi hội phụ nữ Công an xã Bình Nguyên",
  "Chi hội phụ nữ Công an xã Bình Phú",
  "Chi hội phụ nữ Công an xã Bình Tuyền",
  "Chi hội phụ nữ Công an xã Bình Xuyên",
  "Chi hội phụ nữ Công an xã Cẩm Khê",
  "Chi hội phụ nữ Công an xã Cao Dương",
  "Chi hội phụ nữ Công an xã Cao Phong",
  "Chi hội phụ nữ Công an xã Cao Sơn",
  "Chi hội phụ nữ Công an xã Chân Mộng",
  "Chi hội phụ nữ Công an xã Chí Đám",
  "Chi hội phụ nữ Công an xã Chí Tiên",
  "Chi hội phụ nữ Công an xã Cự Đồng",
  "Chi hội phụ nữ Công an xã Đà Bắc",
  "Chi hội phụ nữ Công an xã Đại Đình",
  "Chi hội phụ nữ Công an xã Đại Đồng",
  "Chi hội phụ nữ Công an xã Dân Chủ",
  "Chi hội phụ nữ Công an xã Đan Thượng",
  "Chi hội phụ nữ Công an xã Đạo Trù",
  "Chi hội phụ nữ Công an xã Đào Xá",
  "Chi hội phụ nữ Công an xã Đoan Hùng",
  "Chi hội phụ nữ Công an xã Đồng Lương",
  "Chi hội phụ nữ Công an xã Đông Thành",
  "Chi hội phụ nữ Công an xã Đức Nhàn",
  "Chi hội phụ nữ Công an xã Dũng Tiến",
  "Chi hội phụ nữ Công an xã Hạ Hoà",
  "Chi hội phụ nữ Công an xã Hải Lựu",
  "Chi hội phụ nữ Công an xã Hiền Lương",
  "Chi hội phụ nữ Công an xã Hiền Quan",
  "Chi hội phụ nữ Công an xã Hoàng An",
  "Chi hội phụ nữ Công an xã Hoàng Cương",
  "Chi hội phụ nữ Công an xã Hội Thịnh",
  "Chi hội phụ nữ Công an xã Hợp Kim",
  "Chi hội phụ nữ Công an xã Hợp Lý",
  "Chi hội phụ nữ Công an xã Hùng Việt",
  "Chi hội phụ nữ Công an xã Hương Cần",
  "Chi hội phụ nữ Công an xã Hy Cương",
  "Chi hội phụ nữ Công an xã Khả Cửu",
  "Chi hội phụ nữ Công an xã Kim Bôi",
  "Chi hội phụ nữ Công an xã Lạc Lương",
  "Chi hội phụ nữ Công an xã Lạc Sơn",
  "Chi hội phụ nữ Công an xã Lạc Thủy",
  "Chi hội phụ nữ Công an xã Lai Đồng",
  "Chi hội phụ nữ Công an xã Lâm Thao",
  "Chi hội phụ nữ Công an xã Lập Thạch",
  "Chi hội phụ nữ Công an xã Liên Châu",
  "Chi hội phụ nữ Công an xã Liên Hòa",
  "Chi hội phụ nữ Công an xã Liên Minh",
  "Chi hội phụ nữ Công an xã Liên Sơn",
  "Chi hội phụ nữ Công an xã Long Cốc",
  "Chi hội phụ nữ Công an xã Lương Sơn",
  "Chi hội phụ nữ Công an xã Mai Châu",
  "Chi hội phụ nữ Công an xã Mai Hạ",
  "Chi hội phụ nữ Công an xã Minh Đài",
  "Chi hội phụ nữ Công an xã Minh Hoà",
  "Chi hội phụ nữ Công an xã Mường Bi",
  "Chi hội phụ nữ Công an xã Mường Động",
  "Chi hội phụ nữ Công an xã Mường Hoa",
  "Chi hội phụ nữ Công an xã Mường Thàng",
  "Chi hội phụ nữ Công an xã Mường Vang",
  "Chi hội phụ nữ Công an xã Nật Sơn",
  "Chi hội phụ nữ Công an xã Ngọc Sơn",
  "Chi hội phụ nữ Công an xã Nguyệt Đức",
  "Chi hội phụ nữ Công an xã Nhân Nghĩa",
  "Chi hội phụ nữ Công an xã Pà Cò",
  "Chi hội phụ nữ Công an xã Phú Khê",
  "Chi hội phụ nữ Công an xã Phú Mỹ",
  "Chi hội phụ nữ Công an xã Phù Ninh",
  "Chi hội phụ nữ Công an xã Phùng Nguyên",
  "Chi hội phụ nữ Công an xã Quảng Yên",
  "Chi hội phụ nữ Công an xã Quy Đức",
  "Chi hội phụ nữ Công an xã Quyết Thắng",
  "Chi hội phụ nữ Công an xã Sơn Đông",
  "Chi hội phụ nữ Công an xã Sơn Lương",
  "Chi hội phụ nữ Công an xã Sông Lô",
  "Chi hội phụ nữ Công an xã Tam Đảo",
  "Chi hội phụ nữ Công an xã Tam Dương",
  "Chi hội phụ nữ Công an xã Tam Dương Bắc",
  "Chi hội phụ nữ Công an xã Tam Hồng",
  "Chi hội phụ nữ Công an xã Tam Nông",
  "Chi hội phụ nữ Công an xã Tam Sơn",
  "Chi hội phụ nữ Công an xã Tân Lạc",
  "Chi hội phụ nữ Công an xã Tân Mai",
  "Chi hội phụ nữ Công an xã Tân Pheo",
  "Chi hội phụ nữ Công an xã Tân Sơn",
  "Chi hội phụ nữ Công an xã Tây Cốc",
  "Chi hội phụ nữ Công an xã Tề Lỗ",
  "Chi hội phụ nữ Công an xã Thái Hòa",
  "Chi hội phụ nữ Công an xã Thanh Ba",
  "Chi hội phụ nữ Công an xã Thanh Sơn",
  "Chi hội phụ nữ Công an xã Thanh Thuỷ",
  "Chi hội phụ nữ Công an xã Thịnh Minh",
  "Chi hội phụ nữ Công an xã Thổ Tang",
  "Chi hội phụ nữ Công an xã Thọ Văn",
  "Chi hội phụ nữ Công an xã Thu Cúc",
  "Chi hội phụ nữ Công an xã Thung Nai",
  "Chi hội phụ nữ Công an xã Thượng Cốc",
  "Chi hội phụ nữ Công an xã Thượng Long",
  "Chi hội phụ nữ Công an xã Tiên Lữ",
  "Chi hội phụ nữ Công an xã Tiên Lương",
  "Chi hội phụ nữ Công an xã Tiền Phong",
  "Chi hội phụ nữ Công an xã Toàn Thắng",
  "Chi hội phụ nữ Công an xã Trạm Thản",
  "Chi hội phụ nữ Công an xã Trung Sơn",
  "Chi hội phụ nữ Công an xã Tu Vũ",
  "Chi hội phụ nữ Công an xã Văn Bán",
  "Chi hội phụ nữ Công an xã Văn Lang",
  "Chi hội phụ nữ Công an xã Văn Miếu",
  "Chi hội phụ nữ Công an xã Vân Sơn",
  "Chi hội phụ nữ Công an xã Vạn Xuân",
  "Chi hội phụ nữ Công an xã Vĩnh An",
  "Chi hội phụ nữ Công an xã Vĩnh Chân",
  "Chi hội phụ nữ Công an xã Vĩnh Hưng",
  "Chi hội phụ nữ Công an xã Vĩnh Phú",
  "Chi hội phụ nữ Công an xã Vĩnh Thành",
  "Chi hội phụ nữ Công an xã Vĩnh Tường",
  "Chi hội phụ nữ Công an xã Võ Miếu",
  "Chi hội phụ nữ Công an xã Xuân Đài",
  "Chi hội phụ nữ Công an xã Xuân Lãng",
  "Chi hội phụ nữ Công an xã Xuân Lũng",
  "Chi hội phụ nữ Công an xã Xuân Viên",
  "Chi hội phụ nữ Công an xã Yên Kỳ",
  "Chi hội phụ nữ Công an xã Yên Lạc",
  "Chi hội phụ nữ Công an xã Yên Lãng",
  "Chi hội phụ nữ Công an xã Yên Lập",
  "Chi hội phụ nữ Công an xã Yên Phú",
  "Chi hội phụ nữ Công an xã Yên Sơn",
  "Chi hội phụ nữ Công an xã Yên Thủy",
  "Chi hội phụ nữ Công an xã Yên Trị",
  "Chi hội phụ nữ Phòng PA01",
  "Chi hội phụ nữ Phòng PA02",
  "Chi hội phụ nữ Phòng PA03",
  "Chi hội phụ nữ Phòng PA04",
  "Chi hội phụ nữ Phòng PA05",
  "Chi hội phụ nữ Phòng PA06",
  "Chi hội phụ nữ Phòng PA08",
  "Chi hội phụ nữ Phòng PA09",
  "Chi hội phụ nữ Phòng PC01",
  "Chi hội phụ nữ Phòng PC02",
  "Chi hội phụ nữ Phòng PC03",
  "Chi hội phụ nữ Phòng PC04",
  "Chi hội phụ nữ Phòng PC06",
  "Chi hội phụ nữ Phòng PC07",
  "Chi hội phụ nữ Phòng PC08",
  "Chi hội phụ nữ Phòng PC09",
  "Chi hội phụ nữ Phòng PC10",
  "Chi hội phụ nữ Phòng PK02",
  "Chi hội phụ nữ TTG 1",
  "Chi hội phụ nữ TTG 2",
  "Chi hội phụ nữ TTG 3",
  "Chi hội phụ nữ Phòng PV01",
  "Chi hội phụ nữ Phòng PV06",
  "Chi hội phụ nữ Phòng PX01",
  "Chi hội phụ nữ Phòng PX03",
  "Chi hội phụ nữ Phòng PX05",
  "Chi hội phụ nữ Phòng PX06",
  "Chi hội phụ nữ Phòng PH06",
  "Chi hội phụ nữ Phòng PH10"
];
